CC = g++ 
##CFLAGS =  -Wall -g -Ddoubleonly -DGNU -O2 -Dmpipl=300
CFLAGS =  -Wall -g -Ddoubleonly -DGNU -O2
##CFLAGS2 = -I/scratch/rosenberg/WorkReg -L/scratch/rosenberg/WorkReg
CFLAGS2 = -I$(HOME)/include -L$(HOME)/lib

FFLAGS = -O2

OBJSPL = nrutil.o

#LIBS = -lf2c -lg++ -lm
LIBS = -L$(HOME)/lib -lmp -lf2c 

.C.o:
	$(CC) $(CFLAGS) $(CFLAGS2) -c $*.C


all:Linpol mp_LIPGauss mp_LIPRealGauss GaussLIP

Linpol:Linpol.o $(OBJSPL)
	$(CC) -o Linpol $(CFLAGS) $(CFLAGS2) Linpol.o $(OBJSPL)

mp_LIPGauss:mp_LIPGauss.o $(OBJSPL)
	$(CC) -o mp_LIPGauss $(CFLAGS) $(CFLAGS2) mp_LIPGauss.o $(OBJSPL) $(LIBS)

mp_LIPRealGauss:mp_LIPRealGauss.o $(OBJSPL)
	$(CC) -o mp_LIPRealGauss $(CFLAGS) $(CFLAGS2) mp_LIPRealGauss.o $(OBJSPL) $(LIBS)

GaussLIP:GaussLIP.o $(OBJSPL)
	$(CC) -o GaussLIP $(CFLAGS) $(CFLAGS2) GaussLIP.o $(OBJSPL) $(LIBS)


clean:
	rm -f *.o *~

