extern double e1data(double x);
extern double e2data(double x);
extern double e1datagauss(double x, double beta, int N = 1000);
extern double e2datagauss(double x, double beta, int N = 1000);
extern double e1datagauss_exakt(double x, double beta, int N = 1000);
extern double e2datagauss_exakt(double x, double beta, int N = 1000);
extern double e2data_multi_gauss(double x, double beta1, double t1, double beta2, double t2, double a, int N = 1000);


